Fix for tasks extras
obsidian-tasks-group/obsidian-tasks-custom-icons pull request #14
Opened 2024-08-30 12:21 UTC by salem404

2024-08-30 12:49 UTC, claremacrae commented
Hi @replete If/when you have time, could you review this please? Many thanks!

2024-08-30 13:53 UTC, replete commented
Hi @salem404, thanks for contributing to this, people will appreciate it working with new Tasks features.

I'm not using tasks anymore and this little project is in need of a new maintainer since handing off, and I'm not set up for testing this easily right now.

if you are up for it I have a request to make this more maintainable and testable:
- Create a blank obsidian vault to a new folder in repo named `_vault`
    - add `Tasks` plugin from community plugins
    - create a note with some tasks with all the features in use (for testing)
- exclude the .vault folder by changing end of line 17 of index.js from `.match(/\.git|node_modules/));` to `.match(/\.git|node_modules|_vault/));`
- (optional bonus) with this vault added, we could add `copysnippetpath.txt` (file content: `_vault/.snippets/`) to one of the lucide dirs with contents of  to automatically copy the generated CSS into the demo vault when you run `npm run build`. Unfortunately right now it doesn't support relative paths, so a fix is needed in `index.js` to support relative paths, which is probably using nodes `path` module with something like `path.resolve()` to get the absolute path. If node isn't your thing, don't worry we can test the snippet manually.

Otherwise, someone else with more time needs to test this makes sense before accepting it. The important thing is that the changes you've made aren't overly specific to a theme, e.g. the margins.

Once its good to go, I would recommend a version bump to `v1.0.5`, `npm run build`, remove the `/* fix for ...` comments and merge as the new version.

2024-08-30 16:41 UTC, claremacrae commented
@salem404, let me know if you would me to create the sample value and add it to this PR..

I have the sample tasks ready already in the Tasks plugin docs and can copy them in here very quickly.

2024-08-30 16:59 UTC, claremacrae commented
> @salem404, let me know if you would me to create the sample value and add it to this PR..

Oh no, I don't think that is going to be safe because the PR is created from your `main` rather than a branch.

2024-08-30 17:57 UTC, claremacrae commented
Here are screenshots of the before and after from this PR

| Name | Before PR #14 | After PR #14  |
|--------|--------|--------|
| TasksMonoEmojis-emojitwo.css  | ![image](https://github.com/user-attachments/assets/8935c4b4-4399-458e-a948-5e50077aa314)  | ![image](https://github.com/user-attachments/assets/12f79faf-57b3-4f53-aa78-d68ba3e16623)  |
| TasksMonoEmojis-lucide.css | ![image](https://github.com/user-attachments/assets/84b99ef0-25f4-42fb-a6dc-689d689b2658)  |  ![image](https://github.com/user-attachments/assets/8683f7a7-0833-4fb8-b4a6-44227348107d)  |
|TasksMonoEmojis-lucide2.css | ![image](https://github.com/user-attachments/assets/c8ca2dff-e2be-4aa1-be9a-5de60013473a)  | ![image](https://github.com/user-attachments/assets/5b90b7c2-52e0-48b6-98e8-c575c702d4ac)  |
| TasksMonoEmojis-notoemoji.css | ![image](https://github.com/user-attachments/assets/da5ea3f6-125e-4b13-89e7-18c1b83859eb)  | ![image](https://github.com/user-attachments/assets/a30ecd43-33f9-4910-99df-a3ffc89f3126)  |

2024-08-30 18:02 UTC, claremacrae reviewed
Summary of the effects of the changes....

2024-08-30 18:02 UTC, claremacrae commented on TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css
> +  font-family: "${fontName}", var(--font-text);
This change breaks the styling of all emojis - perhaps because 'TasksMonoEmojis' is replaced by "${fontName}".

2024-08-30 18:02 UTC, claremacrae commented on TasksMonoEmojis-emojitwo/TasksMonoEmojis-emojitwo.css
This change affects the rending of the Pencil icon,

Left: Before
Right: After

![image](https://github.com/user-attachments/assets/90d13585-a499-4672-be57-075986c08da9)

2024-08-30 18:02 UTC, claremacrae commented on TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css
> +  font-family: "${fontName}", var(--font-text);
Left: Before
Right: After

![image](https://github.com/user-attachments/assets/64c7f0b0-3230-4b30-913e-1d87c20d07f2)

2024-08-30 18:02 UTC, claremacrae commented on TasksMonoEmojis-lucide2/TasksMonoEmojis-lucide2.css
This change is great - it styles the Pencil and Postpone buttons:

![image](https://github.com/user-attachments/assets/4b0168c6-6c0f-489e-aaba-d685eba30235)

2024-08-30 18:02 UTC, claremacrae commented on TasksMonoEmojis-notoemoji/TasksMonoEmojis-notoemoji.css
This change breaks the Pencil icon:

![image](https://github.com/user-attachments/assets/5eaf32d0-4720-4d4e-ad76-8abed6ce56e7)

2024-08-30 18:55 UTC, claremacrae requested changes
Thanks for the updates!

2024-08-30 18:55 UTC, claremacrae commented on index.js
> +    .filter((file) => fs.statSync(`${path}/${file}`).isDirectory())
Please could you revert all the formatting changes here, and elsewhere, so that the diff shows just the code that has changed?

Thanks.

2024-08-30 18:55 UTC, claremacrae commented on package.json
> +    "xml2js": "^0.6.2"
For my own education, what's the reason for the new dependencies?

2024-08-30 18:55 UTC, claremacrae commented on package-lock.json
There are a lot of changes in this file - I don't have the knowledge to review these changes, but can't see how the relate to the CSS changes...

2024-08-30 18:55 UTC, claremacrae commented on _vault/Note.md
> +- [ ] task full emoji 📅 2024-08-30 🛫 2024-08-30 ⏳ 2024-08-30 ⏫ 🔁 every day ➕ 2024-08-30 🆔 ikp3n1 ⛔ 🏁 delete  [id:: iwgbhh]
There's a lot of missing emojis here, but don't worry, I'll add the missing ones after the PR is merged...

2024-08-30 19:04 UTC, salem404 commented on package.json
> +    "xml2js": "^0.6.2"
Leftovers from my testing! Not really neccesary

2024-08-30 21:14 UTC, claremacrae reviewed
Thanks very much for the fixes.

2 of the 4 sets are working great now.

If we can just fix the pencil icons in the other two, I think it'll be good to go....

2024-08-30 21:14 UTC, claremacrae commented on TasksMonoEmojis-lucide/TasksMonoEmojis-lucide.css
> +  font-family: "${fontName}", var(--font-text);
Confirmed - this is fixed.

(It took me a long time to discover that though, as I hadn't spotted that the sample vault was set to dataview format, and so the postpone button was missing from my (Tasks emoji) tasks with due dates!)

2024-08-30 21:14 UTC, claremacrae commented on TasksMonoEmojis-emojitwo/TasksMonoEmojis-emojitwo.css
I see that you've marked this as resolved, but for me, I am still getting the same non-obvious, non-pencil icons for the two non-lucide sets...

I presume it's because @replete kindly added the recent icons to the two Lucide ones and not to the other two...

![image](https://github.com/user-attachments/assets/cffa98b7-3ca3-4c82-9d67-d0597327d1b3)

2024-08-30 21:14 UTC, claremacrae commented on TasksMonoEmojis-notoemoji/TasksMonoEmojis-notoemoji.css
Unresolving for visibility, as this still has the purple bars for the Pencil icon..

2024-08-30 21:14 UTC, claremacrae commented on package-lock.json
> +      "integrity": "sha512-BcYH1CVJBO9tvyIZ2jVeXgSIMvGZ2FDRvDdOIVQyuklNKSsx+eppDEBq/g47Ayw+RqNFE+URvOShmf+f/qwAlA==",
I see the changes in version numbers remain here, but as this change doesn't affect the generated CSS it's not worth spending more time on - it's fine for these changes to remain....

2024-08-30 21:14 UTC, claremacrae commented on copysnippetpath.txt
I spent a while trying to work out why the file in the snippets folder wasn't being updated, and then realised that this needs to be copied in to the `TasksMonoEmojis.../` sub-folders.

And that once there, they are .git-ignored...

This is fine for now. We can consider later how to streamline this...

2024-08-30 21:14 UTC, claremacrae commented on TasksMonoEmojis-notoemoji/TasksMonoEmojis-notoemoji.css
> +  content: "󱖉";
What is this character?

2024-08-31 09:19 UTC, replete commented
FYI to bump the version number:
- update the `version` property in `./package.json` to `1.0.5`
- run `npm run build`

2024-08-31 09:21 UTC, replete commented
Great to see this used and worked on by the way. Hopefully one day someone develops some proper Tasks icons and tweaks this to look amazing. 

Emoji two is incomplete because it was missing icons, Noto Emoji was difficult to use because it involved extracting SVGs from Google's font (and also they looked bad IMO). 

Good PR

2024-08-31 10:14 UTC, salem404 commented on TasksMonoEmojis-notoemoji/TasksMonoEmojis-notoemoji.css
> +  content: "󱖉";
uF1589, i dont think its an emoji. Some images name unicodes dont match with the emojis they are supossed to replace. I'll try to fix that

2024-08-31 13:58 UTC, salem404 commented on TasksMonoEmojis-notoemoji/TasksMonoEmojis-notoemoji.css
should be fixed now

2024-09-01 22:38 UTC, claremacrae commented
Hi @salem404, many thanks for the extra commit you pushed yesterday.

I will review it on Mac, iOS, iPad and Windows as soon as I can.

2024-09-02 13:10 UTC, replete commented
@claremacrae FYI it's still broken on iOS, open issue on repo. Something to do with Safari (I call Safari the new Internet Explorer these days) being fussy about CSS `unicode-ranges` format

2024-09-02 13:56 UTC, claremacrae commented
> @claremacrae FYI it's still broken on iOS, open issue on repo. Something to do with Safari (I call Safari the new Internet Explorer these days) being fussy about CSS `unicode-ranges` format

Thanks Phil.

I thought that you had fixed it Previously:
https://github.com/search?q=repo%3Aobsidian-tasks-group%2Fobsidian-tasks-custom-icons+safari&type=commits
https://github.com/search?q=repo%3Aobsidian-tasks-group%2Fobsidian-tasks-custom-icons+ios&type=commits

2024-09-02 14:10 UTC, replete commented
@claremacrae I got it to work, but it in my haste broke the other platforms so we rolled back, this is why #3 is still open. 

Safari was fussy about `unicode-range` value format, so this could be fixed by modifying `implementationCSS` in `index.js` to output a slightly different format for the `unicode-range` property value, e.g. `.safari-mobile { @font-face {... } }`.  I think it preferred uppercase Fs, or something. I would recommend another PR to fix that and not block this PR for it.

2024-09-03 19:59 UTC, claremacrae commented
It's looking good, now thanks @salem404!

I don't have time to create a table of all the changes, one image at time - so here are some screenshots from OneNote:

![image](https://github.com/user-attachments/assets/dbbba4c4-b1ee-434c-bd36-76c6ee02e7cf)

![image](https://github.com/user-attachments/assets/45b78670-de55-4e20-be13-3cfbe6d70249)


![image](https://github.com/user-attachments/assets/d6aff271-0827-40ca-a960-fa4508bab990)


![image](https://github.com/user-attachments/assets/b6bbd5d7-d661-4b0e-86f7-606213e85104)

2024-09-03 20:01 UTC, claremacrae approved these changes

2024-09-03 20:04 UTC, merged

2024-09-03 20:07 UTC, claremacrae commented
Hi @salem404 - many many thanks for this!

Just to note that I squashed the PR because of the formatting changes (thanks for reverting them), to keep `got annotate` useful.

I see that you committed the changes on your `main`, so I'm not sure how it's going to work for you to get the latest code on to your fork.

You probably know this, but in case it helps in future... in general, it's a good idea to create a branch on your fork when making changes to go in a pull request....

Again, thanks!